apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      nodeSelector:
        db: mongodb
      containers:
        - name: notification-service
          image: dusky88/nms_notification-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: PORT
              value: "3003"
            - name: NODE_ENV
              value: "production"